[project]
name = "python-advanced-working-with-restful-apis"
version = "0.1.0"
authors = [
    {name = "Piotr OpaÅ‚a", email = "opalapj@gmail.com"},
]
license = {text = "MIT"}
dependencies = ["requests>=2.32.5"]
requires-python = "==3.13.*"

[tool.pdm]
distribution = false
